#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../..");
const manifestPath = resolve(repoRoot, "schemas/app-server/roder-app-server.v1.json");
const defaultOutput = resolve(repoRoot, "sdk/python/src/roder_sdk/types_generated.py");

const args = process.argv.slice(2);
const check = args.includes("--check");
const output = optionValue(args, "--output") ?? defaultOutput;

const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const text = render(manifest);

if (check) {
  const current = readFileSync(output, "utf8");
  if (current !== text) {
    console.error(`${relative(output)} is stale; run node sdk/codegen/generate-python.mjs`);
    process.exit(1);
  }
} else {
  await mkdir(dirname(output), { recursive: true });
  writeFileSync(output, text);
}

function render(manifest) {
  const methods = manifest.methods.map((method) => method.method);
  return `# Generated by sdk/codegen/generate-python.mjs. Do not edit.

from __future__ import annotations

from typing import Any, Literal, TypeAlias, TypedDict

APP_SERVER_MANIFEST: dict[str, Any] = ${pythonLiteral(manifest)}

APP_SERVER_METHODS: tuple[str, ...] = ${pythonTuple(methods)}

AppServerMethod: TypeAlias = Literal[${methods.map((method) => JSON.stringify(method)).join(", ")}]


class JsonRpcError(TypedDict, total=False):
    code: int
    message: str
    data: Any


class JsonRpcRequest(TypedDict, total=False):
    jsonrpc: Literal["2.0"]
    id: str | int | None
    method: AppServerMethod
    params: Any


class JsonRpcResponse(TypedDict, total=False):
    jsonrpc: Literal["2.0"]
    id: str | int | None
    result: Any
    error: JsonRpcError
`;
}

function pythonLiteral(value) {
  return JSON.stringify(value, null, 4)
    .replaceAll(": true", ": True")
    .replaceAll(": false", ": False")
    .replaceAll(": null", ": None");
}

function pythonTuple(values) {
  const body = values.map((value) => `    ${JSON.stringify(value)},`).join("\n");
  return `(\n${body}\n)`;
}

function optionValue(args, name) {
  const equals = args.find((arg) => arg.startsWith(`${name}=`));
  if (equals) {
    return equals.slice(name.length + 1);
  }
  const index = args.indexOf(name);
  return index === -1 ? undefined : args[index + 1];
}

function relative(path) {
  return path.startsWith(`${repoRoot}/`) ? path.slice(repoRoot.length + 1) : path;
}
