// Generated by sdk/codegen/generate-typescript.mjs. Do not edit.

export const appServerManifest = {
  "schemaVersion": 1,
  "unknownMethodsAllowed": true,
  "methods": [
    {
      "method": "agents/list",
      "paramsType": "AgentsListParams",
      "resultType": "AgentsListResult",
      "stability": "stable",
      "featureGroup": "agents",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "artifact/delete",
      "paramsType": "ArtifactDeleteParams",
      "resultType": "ArtifactDeleteResult",
      "stability": "stable",
      "featureGroup": "artifacts",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "artifact/grep",
      "paramsType": "ArtifactGrepParams",
      "resultType": "ArtifactGrepResult",
      "stability": "stable",
      "featureGroup": "artifacts",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "artifact/list",
      "paramsType": "ArtifactListParams",
      "resultType": "ArtifactListResult",
      "stability": "stable",
      "featureGroup": "artifacts",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "artifact/read",
      "paramsType": "ArtifactReadParams",
      "resultType": "ArtifactReadResult",
      "stability": "stable",
      "featureGroup": "artifacts",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "artifact/tail",
      "paramsType": "ArtifactTailParams",
      "resultType": "ArtifactTailResult",
      "stability": "stable",
      "featureGroup": "artifacts",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "auth/codex/login",
      "paramsType": "AuthCodexLoginParams",
      "resultType": "AuthCodexLoginResult",
      "stability": "stable",
      "featureGroup": "auth",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "auth/codex/logout",
      "paramsType": "AuthCodexLogoutParams",
      "resultType": "AuthCodexLogoutResult",
      "stability": "stable",
      "featureGroup": "auth",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "auth/codex/status",
      "paramsType": "AuthCodexStatusParams",
      "resultType": "AuthCodexStatusResult",
      "stability": "stable",
      "featureGroup": "auth",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "auth/supergrok/login",
      "paramsType": "AuthSupergrokLoginParams",
      "resultType": "AuthSupergrokLoginResult",
      "stability": "stable",
      "featureGroup": "auth",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "auth/supergrok/logout",
      "paramsType": "AuthSupergrokLogoutParams",
      "resultType": "AuthSupergrokLogoutResult",
      "stability": "stable",
      "featureGroup": "auth",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "auth/supergrok/status",
      "paramsType": "AuthSupergrokStatusParams",
      "resultType": "AuthSupergrokStatusResult",
      "stability": "stable",
      "featureGroup": "auth",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "automations/cancelRun",
      "paramsType": "AutomationsCancelRunParams",
      "resultType": "AutomationsCancelRunResult",
      "stability": "stable",
      "featureGroup": "automations",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "automations/create",
      "paramsType": "AutomationsCreateParams",
      "resultType": "AutomationsCreateResult",
      "stability": "stable",
      "featureGroup": "automations",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "automations/delete",
      "paramsType": "AutomationsDeleteParams",
      "resultType": "AutomationsDeleteResult",
      "stability": "stable",
      "featureGroup": "automations",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "automations/list",
      "paramsType": "AutomationsListParams",
      "resultType": "AutomationsListResult",
      "stability": "stable",
      "featureGroup": "automations",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "automations/runNow",
      "paramsType": "AutomationsRunNowParams",
      "resultType": "AutomationsRunNowResult",
      "stability": "stable",
      "featureGroup": "automations",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "automations/runs",
      "paramsType": "AutomationsRunsParams",
      "resultType": "AutomationsRunsResult",
      "stability": "stable",
      "featureGroup": "automations",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "automations/status",
      "paramsType": "AutomationsStatusParams",
      "resultType": "AutomationsStatusResult",
      "stability": "stable",
      "featureGroup": "automations",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "automations/update",
      "paramsType": "AutomationsUpdateParams",
      "resultType": "AutomationsUpdateResult",
      "stability": "stable",
      "featureGroup": "automations",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "command/exec",
      "paramsType": "CommandExecParams",
      "resultType": "CommandExecResult",
      "stability": "stable",
      "featureGroup": "commands",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "commands/expand",
      "paramsType": "CommandsExpandParams",
      "resultType": "CommandsExpandResult",
      "stability": "stable",
      "featureGroup": "commands",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "commands/list",
      "paramsType": "CommandsListParams",
      "resultType": "CommandsListResult",
      "stability": "stable",
      "featureGroup": "commands",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "commands/run",
      "paramsType": "CommandsRunParams",
      "resultType": "CommandsRunResult",
      "stability": "stable",
      "featureGroup": "commands",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "discovery/groups",
      "paramsType": "DiscoveryGroupsParams",
      "resultType": "DiscoveryGroupsResult",
      "stability": "stable",
      "featureGroup": "discovery",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "discovery/promote",
      "paramsType": "DiscoveryPromoteParams",
      "resultType": "DiscoveryPromoteResult",
      "stability": "stable",
      "featureGroup": "discovery",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "discovery/promoted/clear",
      "paramsType": "DiscoveryPromotedClearParams",
      "resultType": "DiscoveryPromotedClearResult",
      "stability": "stable",
      "featureGroup": "discovery",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "discovery/promoted/list",
      "paramsType": "DiscoveryPromotedListParams",
      "resultType": "DiscoveryPromotedListResult",
      "stability": "stable",
      "featureGroup": "discovery",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "discovery/read",
      "paramsType": "DiscoveryReadParams",
      "resultType": "DiscoveryReadResult",
      "stability": "stable",
      "featureGroup": "discovery",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "discovery/refresh",
      "paramsType": "DiscoveryRefreshParams",
      "resultType": "DiscoveryRefreshResult",
      "stability": "stable",
      "featureGroup": "discovery",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "discovery/search",
      "paramsType": "DiscoverySearchParams",
      "resultType": "DiscoverySearchResult",
      "stability": "stable",
      "featureGroup": "discovery",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "eval/report/read",
      "paramsType": "EvalReportReadParams",
      "resultType": "EvalReportReadResult",
      "stability": "stable",
      "featureGroup": "eval",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "eval/reports/list",
      "paramsType": "EvalReportsListParams",
      "resultType": "EvalReportsListResult",
      "stability": "stable",
      "featureGroup": "eval",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "extensions/list",
      "paramsType": "ExtensionsListParams",
      "resultType": "ExtensionsListResult",
      "stability": "stable",
      "featureGroup": "extensions",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "fs/readDirectory",
      "paramsType": "FsReadDirectoryParams",
      "resultType": "FsReadDirectoryResult",
      "stability": "stable",
      "featureGroup": "filesystem",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "fs/readFile",
      "paramsType": "FsReadFileParams",
      "resultType": "FsReadFileResult",
      "stability": "stable",
      "featureGroup": "filesystem",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "hunk/list",
      "paramsType": "HunkListParams",
      "resultType": "HunkListResult",
      "stability": "stable",
      "featureGroup": "plan-review",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "hunk/read",
      "paramsType": "HunkReadParams",
      "resultType": "HunkReadResult",
      "stability": "stable",
      "featureGroup": "plan-review",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "hunk/rollback",
      "paramsType": "HunkRollbackParams",
      "resultType": "HunkRollbackResult",
      "stability": "stable",
      "featureGroup": "plan-review",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "index/proofs/list",
      "paramsType": "IndexProofsListParams",
      "resultType": "IndexProofsListResult",
      "stability": "stable",
      "featureGroup": "code-index",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "index/readChunk",
      "paramsType": "IndexReadChunkParams",
      "resultType": "IndexReadChunkResult",
      "stability": "stable",
      "featureGroup": "code-index",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "index/rebuild",
      "paramsType": "IndexRebuildParams",
      "resultType": "IndexRebuildResult",
      "stability": "stable",
      "featureGroup": "code-index",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "index/search",
      "paramsType": "IndexSearchParams",
      "resultType": "IndexSearchResult",
      "stability": "stable",
      "featureGroup": "code-index",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "index/status",
      "paramsType": "IndexStatusParams",
      "resultType": "IndexStatusResult",
      "stability": "stable",
      "featureGroup": "code-index",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "initialize",
      "paramsType": "InitializeParams",
      "resultType": "InitializeResult",
      "stability": "stable",
      "featureGroup": "app",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "marketplaces/add",
      "paramsType": "MarketplacesAddParams",
      "resultType": "MarketplacesAddResult",
      "stability": "stable",
      "featureGroup": "marketplaces",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "marketplaces/install_default",
      "paramsType": "MarketplacesInstallDefaultParams",
      "resultType": "MarketplacesInstallDefaultResult",
      "stability": "stable",
      "featureGroup": "marketplaces",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "marketplaces/list",
      "paramsType": "MarketplacesListParams",
      "resultType": "MarketplacesListResult",
      "stability": "stable",
      "featureGroup": "marketplaces",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "marketplaces/plugin",
      "paramsType": "MarketplacesPluginParams",
      "resultType": "MarketplacesPluginResult",
      "stability": "stable",
      "featureGroup": "marketplaces",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "marketplaces/refresh",
      "paramsType": "MarketplacesRefreshParams",
      "resultType": "MarketplacesRefreshResult",
      "stability": "stable",
      "featureGroup": "marketplaces",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "marketplaces/remove",
      "paramsType": "MarketplacesRemoveParams",
      "resultType": "MarketplacesRemoveResult",
      "stability": "stable",
      "featureGroup": "marketplaces",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "marketplaces/search",
      "paramsType": "MarketplacesSearchParams",
      "resultType": "MarketplacesSearchResult",
      "stability": "stable",
      "featureGroup": "marketplaces",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "media/attachToTurn",
      "paramsType": "MediaAttachToTurnParams",
      "resultType": "MediaAttachToTurnResult",
      "stability": "stable",
      "featureGroup": "media",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "media/delete",
      "paramsType": "MediaDeleteParams",
      "resultType": "MediaDeleteResult",
      "stability": "stable",
      "featureGroup": "media",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "media/list",
      "paramsType": "MediaListParams",
      "resultType": "MediaListResult",
      "stability": "stable",
      "featureGroup": "media",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "media/read",
      "paramsType": "MediaReadParams",
      "resultType": "MediaReadResult",
      "stability": "stable",
      "featureGroup": "media",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "media/thumbnail",
      "paramsType": "MediaThumbnailParams",
      "resultType": "MediaThumbnailResult",
      "stability": "stable",
      "featureGroup": "media",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "memory/delete",
      "paramsType": "MemoryDeleteParams",
      "resultType": "MemoryDeleteResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "memory/list",
      "paramsType": "MemoryListParams",
      "resultType": "MemoryListResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "memory/provider/list",
      "paramsType": "MemoryProviderListParams",
      "resultType": "MemoryProviderListResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "memory/provider/set",
      "paramsType": "MemoryProviderSetParams",
      "resultType": "MemoryProviderSetResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "memory/query",
      "paramsType": "MemoryQueryParams",
      "resultType": "MemoryQueryResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "memory/read",
      "paramsType": "MemoryReadParams",
      "resultType": "MemoryReadResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "memory/recall/preview",
      "paramsType": "MemoryRecallPreviewParams",
      "resultType": "MemoryRecallPreviewResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "memory/save",
      "paramsType": "MemorySaveParams",
      "resultType": "MemorySaveResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "memory/update",
      "paramsType": "MemoryUpdateParams",
      "resultType": "MemoryUpdateResult",
      "stability": "stable",
      "featureGroup": "memory",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "model/list",
      "paramsType": "ModelListParams",
      "resultType": "ModelListResult",
      "stability": "stable",
      "featureGroup": "models",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "plan/review/approve",
      "paramsType": "PlanReviewApproveParams",
      "resultType": "PlanReviewApproveResult",
      "stability": "stable",
      "featureGroup": "plan-review",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "plan/review/comment",
      "paramsType": "PlanReviewCommentParams",
      "resultType": "PlanReviewCommentResult",
      "stability": "stable",
      "featureGroup": "plan-review",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "plan/review/read",
      "paramsType": "PlanReviewReadParams",
      "resultType": "PlanReviewReadResult",
      "stability": "stable",
      "featureGroup": "plan-review",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "plan/review/reject",
      "paramsType": "PlanReviewRejectParams",
      "resultType": "PlanReviewRejectResult",
      "stability": "stable",
      "featureGroup": "plan-review",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "plan/review/rewrite",
      "paramsType": "PlanReviewRewriteParams",
      "resultType": "PlanReviewRewriteResult",
      "stability": "stable",
      "featureGroup": "plan-review",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "plugins/disable",
      "paramsType": "PluginsDisableParams",
      "resultType": "PluginsDisableResult",
      "stability": "stable",
      "featureGroup": "plugins",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "plugins/install",
      "paramsType": "PluginsInstallParams",
      "resultType": "PluginsInstallResult",
      "stability": "stable",
      "featureGroup": "plugins",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "plugins/install_all_variants",
      "paramsType": "PluginsInstallAllVariantsParams",
      "resultType": "PluginsInstallAllVariantsResult",
      "stability": "stable",
      "featureGroup": "plugins",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "plugins/list_installed",
      "paramsType": "PluginsListInstalledParams",
      "resultType": "PluginsListInstalledResult",
      "stability": "stable",
      "featureGroup": "plugins",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "plugins/preview_install",
      "paramsType": "PluginsPreviewInstallParams",
      "resultType": "PluginsPreviewInstallResult",
      "stability": "stable",
      "featureGroup": "plugins",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "plugins/uninstall",
      "paramsType": "PluginsUninstallParams",
      "resultType": "PluginsUninstallResult",
      "stability": "stable",
      "featureGroup": "plugins",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "processes/get",
      "paramsType": "ProcessesGetParams",
      "resultType": "ProcessesGetResult",
      "stability": "stable",
      "featureGroup": "processes",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "processes/list",
      "paramsType": "ProcessesListParams",
      "resultType": "ProcessesListResult",
      "stability": "stable",
      "featureGroup": "processes",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "processes/stop",
      "paramsType": "ProcessesStopParams",
      "resultType": "ProcessesStopResult",
      "stability": "stable",
      "featureGroup": "processes",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "processes/stopAll",
      "paramsType": "ProcessesStopAllParams",
      "resultType": "ProcessesStopAllResult",
      "stability": "stable",
      "featureGroup": "processes",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "processes/subscribe",
      "paramsType": "ProcessesSubscribeParams",
      "resultType": "ProcessesSubscribeResult",
      "stability": "stable",
      "featureGroup": "processes",
      "idempotency": "idempotent",
      "sideEffect": "readOnly",
      "notifications": [
        "processes/changed"
      ]
    },
    {
      "method": "providers/clear",
      "paramsType": "ProvidersClearParams",
      "resultType": "ProvidersClearResult",
      "stability": "stable",
      "featureGroup": "providers",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "providers/configure",
      "paramsType": "ProvidersConfigureParams",
      "resultType": "ProvidersConfigureResult",
      "stability": "stable",
      "featureGroup": "providers",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "providers/list",
      "paramsType": "ProvidersListParams",
      "resultType": "ProvidersListResult",
      "stability": "stable",
      "featureGroup": "providers",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "providers/select",
      "paramsType": "ProvidersSelectParams",
      "resultType": "ProvidersSelectResult",
      "stability": "stable",
      "featureGroup": "providers",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "retrieval/metrics",
      "paramsType": "RetrievalMetricsParams",
      "resultType": "RetrievalMetricsResult",
      "stability": "stable",
      "featureGroup": "retrieval",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "retrieval/promoted",
      "paramsType": "RetrievalPromotedParams",
      "resultType": "RetrievalPromotedResult",
      "stability": "stable",
      "featureGroup": "retrieval",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "retrieval/recommendations",
      "paramsType": "RetrievalRecommendationsParams",
      "resultType": "RetrievalRecommendationsResult",
      "stability": "stable",
      "featureGroup": "retrieval",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "roadmap/create",
      "paramsType": "RoadmapCreateParams",
      "resultType": "RoadmapCreateResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "roadmap/list",
      "paramsType": "RoadmapListParams",
      "resultType": "RoadmapListResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "roadmap/patch",
      "paramsType": "RoadmapPatchParams",
      "resultType": "RoadmapPatchResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "roadmap/read",
      "paramsType": "RoadmapReadParams",
      "resultType": "RoadmapReadResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "roadmap/task/update",
      "paramsType": "RoadmapTaskUpdateParams",
      "resultType": "RoadmapTaskUpdateResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "roadmap/thread/attach",
      "paramsType": "RoadmapThreadAttachParams",
      "resultType": "RoadmapThreadAttachResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "roadmap/thread/list",
      "paramsType": "RoadmapThreadListParams",
      "resultType": "RoadmapThreadListResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "roadmap/thread/spawn",
      "paramsType": "RoadmapThreadSpawnParams",
      "resultType": "RoadmapThreadSpawnResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "roadmap/validate",
      "paramsType": "RoadmapValidateParams",
      "resultType": "RoadmapValidateResult",
      "stability": "stable",
      "featureGroup": "roadmap",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "runners/delete",
      "paramsType": "RunnersDeleteParams",
      "resultType": "RunnersDeleteResult",
      "stability": "stable",
      "featureGroup": "runners",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "runners/list",
      "paramsType": "RunnersListParams",
      "resultType": "RunnersListResult",
      "stability": "stable",
      "featureGroup": "runners",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "runners/ports",
      "paramsType": "RunnersPortsParams",
      "resultType": "RunnersPortsResult",
      "stability": "stable",
      "featureGroup": "runners",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "runners/select",
      "paramsType": "RunnersSelectParams",
      "resultType": "RunnersSelectResult",
      "stability": "stable",
      "featureGroup": "runners",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "runners/session",
      "paramsType": "RunnersSessionParams",
      "resultType": "RunnersSessionResult",
      "stability": "stable",
      "featureGroup": "runners",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "runners/snapshot",
      "paramsType": "RunnersSnapshotParams",
      "resultType": "RunnersSnapshotResult",
      "stability": "stable",
      "featureGroup": "runners",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "search_index/clear",
      "paramsType": "SearchIndexClearParams",
      "resultType": "SearchIndexClearResult",
      "stability": "stable",
      "featureGroup": "search-index",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "search_index/rebuild",
      "paramsType": "SearchIndexRebuildParams",
      "resultType": "SearchIndexRebuildResult",
      "stability": "stable",
      "featureGroup": "search-index",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "search_index/status",
      "paramsType": "SearchIndexStatusParams",
      "resultType": "SearchIndexStatusResult",
      "stability": "stable",
      "featureGroup": "search-index",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "search_index/warmup",
      "paramsType": "SearchIndexWarmupParams",
      "resultType": "SearchIndexWarmupResult",
      "stability": "stable",
      "featureGroup": "search-index",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "settings/get",
      "paramsType": "SettingsGetParams",
      "resultType": "SettingsGetResult",
      "stability": "stable",
      "featureGroup": "settings",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "settings/set_default_mode",
      "paramsType": "SettingsSetDefaultModeParams",
      "resultType": "SettingsSetDefaultModeResult",
      "stability": "stable",
      "featureGroup": "settings",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "settings/set_file_backed_dynamic_context",
      "paramsType": "SettingsSetFileBackedDynamicContextParams",
      "resultType": "SettingsSetFileBackedDynamicContextResult",
      "stability": "stable",
      "featureGroup": "settings",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "settings/set_search_index",
      "paramsType": "SettingsSetSearchIndexParams",
      "resultType": "SettingsSetSearchIndexResult",
      "stability": "stable",
      "featureGroup": "settings",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "settings/set_shell",
      "paramsType": "SettingsSetShellParams",
      "resultType": "SettingsSetShellResult",
      "stability": "stable",
      "featureGroup": "settings",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "settings/set_web_search",
      "paramsType": "SettingsSetWebSearchParams",
      "resultType": "SettingsSetWebSearchResult",
      "stability": "stable",
      "featureGroup": "settings",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "skills/list",
      "paramsType": "SkillsListParams",
      "resultType": "SkillsListResult",
      "stability": "stable",
      "featureGroup": "skills",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "skills/read",
      "paramsType": "SkillsReadParams",
      "resultType": "SkillsReadResult",
      "stability": "stable",
      "featureGroup": "skills",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "skills/setEnabled",
      "paramsType": "SkillsSetEnabledParams",
      "resultType": "SkillsSetEnabledResult",
      "stability": "stable",
      "featureGroup": "skills",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "skills/setExposure",
      "paramsType": "SkillsSetExposureParams",
      "resultType": "SkillsSetExposureResult",
      "stability": "stable",
      "featureGroup": "skills",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "speech/providers/list",
      "paramsType": "SpeechProvidersListParams",
      "resultType": "SpeechProvidersListResult",
      "stability": "stable",
      "featureGroup": "speech",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "speech/synthesis/providers/list",
      "paramsType": "SpeechSynthesisProvidersListParams",
      "resultType": "SpeechSynthesisProvidersListResult",
      "stability": "stable",
      "featureGroup": "speech",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "speech/synthesize",
      "paramsType": "SpeechSynthesizeParams",
      "resultType": "SpeechSynthesizeResult",
      "stability": "stable",
      "featureGroup": "speech",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "speech/transcribe",
      "paramsType": "SpeechTranscribeParams",
      "resultType": "SpeechTranscribeResult",
      "stability": "stable",
      "featureGroup": "speech",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "tasks/cancel",
      "paramsType": "TasksCancelParams",
      "resultType": "TasksCancelResult",
      "stability": "stable",
      "featureGroup": "tasks",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "tasks/get",
      "paramsType": "TasksGetParams",
      "resultType": "TasksGetResult",
      "stability": "stable",
      "featureGroup": "tasks",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "tasks/list",
      "paramsType": "TasksListParams",
      "resultType": "TasksListResult",
      "stability": "stable",
      "featureGroup": "tasks",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "tasks/submit",
      "paramsType": "TasksSubmitParams",
      "resultType": "TasksSubmitResult",
      "stability": "stable",
      "featureGroup": "tasks",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "tasks/subscribe",
      "paramsType": "TasksSubscribeParams",
      "resultType": "TasksSubscribeResult",
      "stability": "stable",
      "featureGroup": "tasks",
      "idempotency": "idempotent",
      "sideEffect": "readOnly",
      "notifications": [
        "task.started",
        "task.output",
        "task.completed",
        "task.failed",
        "task.cancelled"
      ]
    },
    {
      "method": "team/cleanup",
      "paramsType": "TeamCleanupParams",
      "resultType": "TeamCleanupResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "team/list",
      "paramsType": "TeamListParams",
      "resultType": "TeamListResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "team/member/focus",
      "paramsType": "TeamMemberFocusParams",
      "resultType": "TeamMemberFocusResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "team/member/interrupt",
      "paramsType": "TeamMemberInterruptParams",
      "resultType": "TeamMemberInterruptResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "team/member/message",
      "paramsType": "TeamMemberMessageParams",
      "resultType": "TeamMemberMessageResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "team/member/start",
      "paramsType": "TeamMemberStartParams",
      "resultType": "TeamMemberStartResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "team/pane/cleanup",
      "paramsType": "TeamPaneCleanupParams",
      "resultType": "TeamPaneCleanupResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "team/pane/focus",
      "paramsType": "TeamPaneFocusParams",
      "resultType": "TeamPaneFocusResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "team/read",
      "paramsType": "TeamReadParams",
      "resultType": "TeamReadResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "team/start",
      "paramsType": "TeamStartParams",
      "resultType": "TeamStartResult",
      "stability": "stable",
      "featureGroup": "teams",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/archive",
      "paramsType": "ThreadArchiveParams",
      "resultType": "ThreadArchiveResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/attach",
      "paramsType": "ThreadAttachParams",
      "resultType": "ThreadAttachResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/exit_plan",
      "paramsType": "ThreadExitPlanParams",
      "resultType": "ThreadExitPlanResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/goal/clear",
      "paramsType": "ThreadGoalClearParams",
      "resultType": "ThreadGoalClearResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState",
      "notifications": [
        "thread/goal/cleared"
      ]
    },
    {
      "method": "thread/goal/get",
      "paramsType": "ThreadGoalGetParams",
      "resultType": "ThreadGoalGetResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "thread/goal/set",
      "paramsType": "ThreadGoalSetParams",
      "resultType": "ThreadGoalSetResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState",
      "notifications": [
        "thread/goal/updated"
      ]
    },
    {
      "method": "thread/list",
      "paramsType": "ThreadListParams",
      "resultType": "ThreadListResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "thread/read",
      "paramsType": "ThreadReadParams",
      "resultType": "ThreadReadResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "thread/resolve_approval",
      "paramsType": "ThreadResolveApprovalParams",
      "resultType": "ThreadResolveApprovalResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/resolve_user_input",
      "paramsType": "ThreadResolveUserInputParams",
      "resultType": "ThreadResolveUserInputResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/roadmap/open",
      "paramsType": "ThreadRoadmapOpenParams",
      "resultType": "ThreadRoadmapOpenResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/set_mode",
      "paramsType": "ThreadSetModeParams",
      "resultType": "ThreadSetModeResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/start",
      "paramsType": "ThreadStartParams",
      "resultType": "ThreadStartResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "thread/state",
      "paramsType": "ThreadStateParams",
      "resultType": "ThreadStateResult",
      "stability": "stable",
      "featureGroup": "thread",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "tools/call",
      "paramsType": "ToolsCallParams",
      "resultType": "ToolsCallResult",
      "stability": "stable",
      "featureGroup": "tools",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "tools/list",
      "paramsType": "ToolsListParams",
      "resultType": "ToolsListResult",
      "stability": "stable",
      "featureGroup": "tools",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "turn/interrupt",
      "paramsType": "TurnInterruptParams",
      "resultType": "TurnInterruptResult",
      "stability": "stable",
      "featureGroup": "turns",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "turn/start",
      "paramsType": "TurnStartParams",
      "resultType": "TurnStartResult",
      "stability": "stable",
      "featureGroup": "turns",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "turn/steer",
      "paramsType": "TurnSteerParams",
      "resultType": "TurnSteerResult",
      "stability": "stable",
      "featureGroup": "turns",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "turn/subagentTrace/read",
      "paramsType": "TurnSubagentTraceReadParams",
      "resultType": "TurnSubagentTraceReadResult",
      "stability": "stable",
      "featureGroup": "turns",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "turn/subagentTraces/list",
      "paramsType": "TurnSubagentTracesListParams",
      "resultType": "TurnSubagentTracesListResult",
      "stability": "stable",
      "featureGroup": "turns",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "vcs/changes/list",
      "paramsType": "VcsChangesListParams",
      "resultType": "VcsChangesListResult",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "vcs/changes/read",
      "paramsType": "VcsChangesReadParams",
      "resultType": "VcsChangedContentPage",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "vcs/lines/list",
      "paramsType": "VcsWorkspaceParams",
      "resultType": "Vec<VcsLineOfWork>",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "vcs/lines/switch",
      "paramsType": "VcsLineSwitchParams",
      "resultType": "VcsOperationResult",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "vcs/restore",
      "paramsType": "VcsRestoreParams",
      "resultType": "VcsOperationResult",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "vcs/select",
      "paramsType": "VcsSelectionParams",
      "resultType": "VcsOperationResult",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "vcs/snapshot/create",
      "paramsType": "VcsSnapshotCreateParams",
      "resultType": "VcsSnapshot",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "vcs/status",
      "paramsType": "VcsWorkspaceParams",
      "resultType": "VcsStatus",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "vcs/sync",
      "paramsType": "VcsSyncParams",
      "resultType": "VcsOperationResult",
      "stability": "stable",
      "featureGroup": "vcs",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "webwright/artifacts",
      "paramsType": "WebwrightArtifactsParams",
      "resultType": "WebwrightArtifactsResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "webwright/export",
      "paramsType": "WebwrightExportParams",
      "resultType": "WebwrightExportResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "webwright/latestRun",
      "paramsType": "WebwrightLatestRunParams",
      "resultType": "WebwrightLatestRunResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "webwright/prepare",
      "paramsType": "WebwrightPrepareParams",
      "resultType": "WebwrightPrepareResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "webwright/report",
      "paramsType": "WebwrightReportParams",
      "resultType": "WebwrightReportResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "webwright/rerun",
      "paramsType": "WebwrightRerunParams",
      "resultType": "WebwrightRerunResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "webwright/setup",
      "paramsType": "WebwrightSetupParams",
      "resultType": "WebwrightSetupResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "nonIdempotent",
      "sideEffect": "externalProcess"
    },
    {
      "method": "webwright/submit",
      "paramsType": "WebwrightSubmitParams",
      "resultType": "WebwrightSubmitResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "webwright/verify",
      "paramsType": "WebwrightVerifyParams",
      "resultType": "WebwrightVerifyResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "webwright/visualJudge",
      "paramsType": "WebwrightVisualJudgeParams",
      "resultType": "WebwrightVisualJudgeResult",
      "stability": "stable",
      "featureGroup": "webwright",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "workflow/enable",
      "paramsType": "WorkflowEnableParams",
      "resultType": "WorkflowEnableResult",
      "stability": "stable",
      "featureGroup": "workflow",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "workflow/ignore",
      "paramsType": "WorkflowIgnoreParams",
      "resultType": "WorkflowIgnoreResult",
      "stability": "stable",
      "featureGroup": "workflow",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "workflow/preview",
      "paramsType": "WorkflowPreviewParams",
      "resultType": "WorkflowPreviewResult",
      "stability": "stable",
      "featureGroup": "workflow",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "workflow/refresh",
      "paramsType": "WorkflowRefreshParams",
      "resultType": "WorkflowRefreshResult",
      "stability": "stable",
      "featureGroup": "workflow",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "workflow/remove",
      "paramsType": "WorkflowRemoveParams",
      "resultType": "WorkflowRemoveResult",
      "stability": "stable",
      "featureGroup": "workflow",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "workflow/scan",
      "paramsType": "WorkflowScanParams",
      "resultType": "WorkflowScanResult",
      "stability": "stable",
      "featureGroup": "workflow",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "workflows/approve",
      "paramsType": "WorkflowsApproveParams",
      "resultType": "WorkflowsApproveResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState",
      "notifications": [
        "workflows/approved",
        "workflows/denied",
        "workflows/queued",
        "workflows/started"
      ]
    },
    {
      "method": "workflows/get",
      "paramsType": "WorkflowsGetParams",
      "resultType": "WorkflowsGetResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "workflows/list",
      "paramsType": "WorkflowsListParams",
      "resultType": "WorkflowsListResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "workflows/pause",
      "paramsType": "WorkflowsPauseParams",
      "resultType": "WorkflowsPauseResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState",
      "notifications": [
        "workflows/paused"
      ]
    },
    {
      "method": "workflows/plan",
      "paramsType": "WorkflowsPlanParams",
      "resultType": "WorkflowsPlanResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState",
      "notifications": [
        "workflows/drafted",
        "workflows/approvalRequested"
      ]
    },
    {
      "method": "workflows/restartAgent",
      "paramsType": "WorkflowsRestartAgentParams",
      "resultType": "WorkflowsRestartAgentResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState",
      "notifications": [
        "workflows/agentQueued",
        "workflows/agentStarted",
        "workflows/agentCompleted",
        "workflows/agentFailed"
      ]
    },
    {
      "method": "workflows/resume",
      "paramsType": "WorkflowsResumeParams",
      "resultType": "WorkflowsResumeResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState",
      "notifications": [
        "workflows/resumed"
      ]
    },
    {
      "method": "workflows/save",
      "paramsType": "WorkflowsSaveParams",
      "resultType": "WorkflowsSaveResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "workflows/scripts/delete",
      "paramsType": "WorkflowsScriptsDeleteParams",
      "resultType": "WorkflowsScriptsDeleteResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState"
    },
    {
      "method": "workflows/scripts/list",
      "paramsType": "WorkflowsScriptsListParams",
      "resultType": "WorkflowsScriptsListResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "workflows/scripts/read",
      "paramsType": "WorkflowsScriptsReadParams",
      "resultType": "WorkflowsScriptsReadResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "idempotent",
      "sideEffect": "readOnly"
    },
    {
      "method": "workflows/stop",
      "paramsType": "WorkflowsStopParams",
      "resultType": "WorkflowsStopResult",
      "stability": "stable",
      "featureGroup": "workflows",
      "idempotency": "nonIdempotent",
      "sideEffect": "localState",
      "notifications": [
        "workflows/stopped"
      ]
    },
    {
      "method": "workspace/changes/list",
      "paramsType": "WorkspaceChangesListParams",
      "resultType": "WorkspaceChangesListResult",
      "stability": "stable",
      "featureGroup": "workspace",
      "idempotency": "idempotent",
      "sideEffect": "readOnly",
      "notifications": [
        "workspace/changeObserved"
      ]
    }
  ]
} as const;

export type AppServerMethod = typeof appServerManifest.methods[number]["method"];

export const appServerMethods = [
  "agents/list",
  "artifact/delete",
  "artifact/grep",
  "artifact/list",
  "artifact/read",
  "artifact/tail",
  "auth/codex/login",
  "auth/codex/logout",
  "auth/codex/status",
  "auth/supergrok/login",
  "auth/supergrok/logout",
  "auth/supergrok/status",
  "automations/cancelRun",
  "automations/create",
  "automations/delete",
  "automations/list",
  "automations/runNow",
  "automations/runs",
  "automations/status",
  "automations/update",
  "command/exec",
  "commands/expand",
  "commands/list",
  "commands/run",
  "discovery/groups",
  "discovery/promote",
  "discovery/promoted/clear",
  "discovery/promoted/list",
  "discovery/read",
  "discovery/refresh",
  "discovery/search",
  "eval/report/read",
  "eval/reports/list",
  "extensions/list",
  "fs/readDirectory",
  "fs/readFile",
  "hunk/list",
  "hunk/read",
  "hunk/rollback",
  "index/proofs/list",
  "index/readChunk",
  "index/rebuild",
  "index/search",
  "index/status",
  "initialize",
  "marketplaces/add",
  "marketplaces/install_default",
  "marketplaces/list",
  "marketplaces/plugin",
  "marketplaces/refresh",
  "marketplaces/remove",
  "marketplaces/search",
  "media/attachToTurn",
  "media/delete",
  "media/list",
  "media/read",
  "media/thumbnail",
  "memory/delete",
  "memory/list",
  "memory/provider/list",
  "memory/provider/set",
  "memory/query",
  "memory/read",
  "memory/recall/preview",
  "memory/save",
  "memory/update",
  "model/list",
  "plan/review/approve",
  "plan/review/comment",
  "plan/review/read",
  "plan/review/reject",
  "plan/review/rewrite",
  "plugins/disable",
  "plugins/install",
  "plugins/install_all_variants",
  "plugins/list_installed",
  "plugins/preview_install",
  "plugins/uninstall",
  "processes/get",
  "processes/list",
  "processes/stop",
  "processes/stopAll",
  "processes/subscribe",
  "providers/clear",
  "providers/configure",
  "providers/list",
  "providers/select",
  "retrieval/metrics",
  "retrieval/promoted",
  "retrieval/recommendations",
  "roadmap/create",
  "roadmap/list",
  "roadmap/patch",
  "roadmap/read",
  "roadmap/task/update",
  "roadmap/thread/attach",
  "roadmap/thread/list",
  "roadmap/thread/spawn",
  "roadmap/validate",
  "runners/delete",
  "runners/list",
  "runners/ports",
  "runners/select",
  "runners/session",
  "runners/snapshot",
  "search_index/clear",
  "search_index/rebuild",
  "search_index/status",
  "search_index/warmup",
  "settings/get",
  "settings/set_default_mode",
  "settings/set_file_backed_dynamic_context",
  "settings/set_search_index",
  "settings/set_shell",
  "settings/set_web_search",
  "skills/list",
  "skills/read",
  "skills/setEnabled",
  "skills/setExposure",
  "speech/providers/list",
  "speech/synthesis/providers/list",
  "speech/synthesize",
  "speech/transcribe",
  "tasks/cancel",
  "tasks/get",
  "tasks/list",
  "tasks/submit",
  "tasks/subscribe",
  "team/cleanup",
  "team/list",
  "team/member/focus",
  "team/member/interrupt",
  "team/member/message",
  "team/member/start",
  "team/pane/cleanup",
  "team/pane/focus",
  "team/read",
  "team/start",
  "thread/archive",
  "thread/attach",
  "thread/exit_plan",
  "thread/goal/clear",
  "thread/goal/get",
  "thread/goal/set",
  "thread/list",
  "thread/read",
  "thread/resolve_approval",
  "thread/resolve_user_input",
  "thread/roadmap/open",
  "thread/set_mode",
  "thread/start",
  "thread/state",
  "tools/call",
  "tools/list",
  "turn/interrupt",
  "turn/start",
  "turn/steer",
  "turn/subagentTrace/read",
  "turn/subagentTraces/list",
  "vcs/changes/list",
  "vcs/changes/read",
  "vcs/lines/list",
  "vcs/lines/switch",
  "vcs/restore",
  "vcs/select",
  "vcs/snapshot/create",
  "vcs/status",
  "vcs/sync",
  "webwright/artifacts",
  "webwright/export",
  "webwright/latestRun",
  "webwright/prepare",
  "webwright/report",
  "webwright/rerun",
  "webwright/setup",
  "webwright/submit",
  "webwright/verify",
  "webwright/visualJudge",
  "workflow/enable",
  "workflow/ignore",
  "workflow/preview",
  "workflow/refresh",
  "workflow/remove",
  "workflow/scan",
  "workflows/approve",
  "workflows/get",
  "workflows/list",
  "workflows/pause",
  "workflows/plan",
  "workflows/restartAgent",
  "workflows/resume",
  "workflows/save",
  "workflows/scripts/delete",
  "workflows/scripts/list",
  "workflows/scripts/read",
  "workflows/stop",
  "workspace/changes/list"
] as const;

export type JsonRpcId = string | number | null;

export interface JsonRpcRequest<M extends AppServerMethod = AppServerMethod, P = unknown> {
  jsonrpc: "2.0";
  id?: JsonRpcId;
  method: M;
  params?: P;
}

export interface JsonRpcError {
  code: number;
  message: string;
  data?: unknown;
}

export interface JsonRpcResponse<R = unknown> {
  jsonrpc: "2.0";
  id?: JsonRpcId;
  result?: R;
  error?: JsonRpcError;
}
