"""Exploration transport: Blaxel CLI authentication, Cua inside one sandbox."""

from __future__ import annotations

import base64
import json
import re
import subprocess
import tempfile


class BlaxelTransport:
    def __init__(self, sandbox: str, workspace: str):
        for label, value in (("sandbox", sandbox), ("workspace", workspace)):
            if not re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9_-]{0,127}", value):
                raise ValueError(f"invalid {label}")
        self.sandbox = sandbox
        self.workspace = workspace

    def run_script(self, script: str, timeout: int = 60) -> dict:
        # Base64 transports code as data and prevents shell interpolation of
        # tool arguments. The CLI reads credentials from its own authenticated
        # store; they never enter protocol frames or the remote command.
        encoded = base64.b64encode(script.encode()).decode()
        command = f"python3 -c 'import base64; exec(base64.b64decode(\"{encoded}\"))'"
        with tempfile.NamedTemporaryFile(mode="w", suffix=".json") as payload:
            json.dump({"command": command, "waitForCompletion": True,
                       "timeout": timeout * 1000, "keepAlive": True}, payload)
            payload.flush()
            result = subprocess.run(
                ["bl", "run", "sandbox", self.sandbox, "--workspace", self.workspace,
                 "--skip-version-warning", "--path", "/process", "--file", payload.name,
                 "--timeout", str(timeout)],
                capture_output=True, text=True, timeout=timeout + 10,
            )
        if result.returncode:
            raise RuntimeError("Blaxel process request failed; inspect authenticated CLI diagnostics")
        try:
            process = json.loads(result.stdout)
        except ValueError as error:
            raise RuntimeError("Blaxel returned a non-JSON process response") from error
        if process.get("status") not in ("completed", "failed"):
            raise RuntimeError("Remote command did not complete; observe current state before retrying input")
        return process

    def call(self, tool: str, arguments: dict) -> tuple[dict, bool]:
        # The session prefix was generated by bootstrap.py inside this sandbox.
        script = (
            "import json,subprocess,pathlib\n"
            "prefix=json.loads(pathlib.Path('/tmp/roder-cua-session.json').read_text())\n"
            f"args={json.dumps(json.dumps(arguments))}\n"
            "command=prefix+['/tmp/roder-cua-driver/cua-driver','call',"
            f"{tool!r},args,'--socket','/tmp/roder-cua.sock']\n"
            "result=subprocess.run(command,capture_output=True,text=True,timeout=45)\n"
            "print(json.dumps({'stdout':result.stdout,'failed':result.returncode!=0}))\n"
        )
        process = self.run_script(script)
        if process.get("exitCode") != 0:
            raise RuntimeError("Remote Cua invocation failed; bootstrap or recovery is required")
        wrapped = json.loads(process.get("stdout", ""))
        try:
            observation = json.loads(wrapped["stdout"])
        except ValueError:
            observation = {"message": wrapped["stdout"]}
        if not isinstance(observation, dict):
            observation = {"result": observation}
        return observation, wrapped["failed"]


def image_result(observation: dict, failed: bool) -> dict:
    """Translate Cua CLI capture into Roder's existing image replay payload."""
    observation = dict(observation)
    encoded = observation.pop("screenshot_png_b64", None)
    mime = observation.pop("screenshot_mime_type", "image/png")
    data = {"observation": observation, "untrusted": True}
    if encoded:
        if mime != "image/png":
            raise ValueError("unexpected Cua screenshot MIME type")
        raw = base64.b64decode(encoded, validate=True)
        if not raw.startswith(b"\x89PNG\r\n\x1a\n") or len(raw) > 8 * 1024 * 1024:
            raise ValueError("invalid or oversized Cua screenshot")
        data["__view_image"] = {
            "image_url": f"data:{mime};base64,{encoded}", "detail": "original"
        }
    return {"content": json.dumps(observation), "data": data, "isError": failed}
